---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/git --version
    register: git_build_test_output
  - debug:
      msg: '{{ git_build_test_output.stdout }}'
