---
- name: Testing andrewrothstein.git_build
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'git --version'
      ansible.builtin.command: git --version
      changed_when: false
      register: git_build_test_output
    - name: Output of 'git --version'
      ansible.builtin.debug:
        msg: '{{ git_build_test_output.stdout }}'
